name: C/C++/CUDA CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: linux-gpu

    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: ./.github/config/configure.sh
    - name: Make
      run: make linux
